NotesUserInterface/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NotesUserInterface.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NotesUserInterface/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NotesUserInterface.Controllers
{
    public class NotesController : Controller
    {
        // GET: Notes
        public ActionResult Index()
        {
            return View();
        }
    }
}

NotesUserInterface/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NotesUserInterface/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NotesUserInterface/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NotesUserInterface/Views/Notes/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2 class="page-header">Notes Application</h2>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<style>

    .page-header {
        text-align: center;
        margin: 25px;
    }
    #tblGetListofNotes {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

        #tblGetListofNotes td, #tblGetListofNotes th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #tblGetListofNotes tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #tblGetListofNotes tr:hover {
            background-color: #ddd;
        }

        #tblGetListofNotes th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #04AA6D;
            color: white;
        }
    div {
        margin-bottom: 5px;
    }

    label {
        display: inline-block;
        width: 110px;
        color: #777777;
    }

    input {
        padding: 5px 10px;
    }


    #hyperlinks {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }
  
</style>

    <div id="hyperlinks">
        <a href="@Url.Action("Index","Notes")" id="showCreateNotes">Create Notes</a>
        <br />

        <a href="@Url.Action("Index","Notes")" id="showNotesList">Get Notes List</a><br />

        <a href="@Url.Action("Index","Notes")" id="UpdateNotesList">Update Notes</a><br />


        <a href="@Url.Action("Index","Notes")" id="DeleteNotesList">Delete Notes</a><br /><br /><br />

    </div>

    <div id="formContainer">
        <!-- Get Notes Container -->
        <div id="GetNotesContainer" style="display: none;">
            <h4> Get List of Notes</h4>
            <form id="GetNote">
                <table id="tblGetListofNotes">
                    <tr>
                        <th>NoteId</th>
                        <th>NoteName</th>
                        <th>Description</th>
                    </tr>
                    <tr>
                        <td>
                            1
                        </td>
                        <td>
                            Test
                        </td>
                        <td>
                            First Note
                        </td>
                    </tr>
                </table>
            </form>
        </div>

        <!-- Create Notes Container -->
        <div id="CreateNotesContainer" style="display: none;">
            <form id="myNote">
                <h4>Create New Notes</h4>
                <div>
                    <label for="title">Note Name</label>
                    <input type="text" id="title" name="NoteName" autofocus><br />
                </div>
                <div>
                    <label for="description">Note Description</label>
                    <textarea id="desc" name="desc"></textarea>
                </div>
                <input type="submit" value="Submit" />
            </form>
            </div>
                <!-- Update Notes Container -->
        <div id="UpdateNotesContainer" style="display: none;">
           
            <form id="UpdateNote">
                <h4> Update with NoteId</h4>
                <label for="title">Note Id</label><br>
                <input type="text" id="Nid" name="NoteId"><br>
                <label for="title">Note Name</label>
                <input style="padding-left:5em; " type="text" id="noteName" name="NoteName"><br /> <br />
                <label for="description">Note Description</label>
                <textarea id="desc" name="desc"></textarea>
                <input type="submit" value="Update">
            </form>
        </div>

                @* Delete Notes Container *@

    <div id="DeleteNotesContainer" style="display: none;">
        <form id="DeleteNote">
            <h4 style="align-content:center;"> Enter your Note ID </h4>
            <label for="title">Note Id</label><br>
            <input type="text" id="Nid" name="NoteId"><br>

            <br /> <br />
            <input type="submit" value="Delete">
        </form>
    </div>
        </div>
        <script src="~/Scripts/Notes.js"></script>
        <script>
            $(document).ready(function () {
                $('#showCreateNotes').click(function () {
                    event.preventDefault();
                    $('#GetNotesContainer').hide();
                    $('#UpdateNotesContainer').hide();
                    $('#DeleteNotesContainer').hide();
                    $('#CreateNotesContainer').show();
                });
                $('#showNotesList').click(function () {
                    event.preventDefault();
                    $('#CreateNotesContainer').hide();
                    $('#UpdateNotesContainer').hide();
                    $('#DeleteNotesContainer').hide();
                    $('#GetNotesContainer').show();
                });
                $('#UpdateNotesList').click(function () {
                    event.preventDefault();
                    $('#CreateNotesContainer').hide();
                    $('#GetNotesContainer').hide();
                    $('#DeleteNotesContainer').hide();
                    $('#UpdateNotesContainer').show();
                });

                $('#DeleteNotesList').click(function () {
                    event.preventDefault();
                    $('#CreateNotesContainer').hide();
                    $('#GetNotesContainer').hide();
                    $('#UpdateNotesContainer').hide();
                    $('#DeleteNotesContainer').show();
                });
            });
        </script>

NotesUserInterface/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    <li>@Html.ActionLink("NotesSection", "Index", "Notes")</li>
                    @*<li>@Html.ActionLink("CreateNotes", "Create", "Notes")</li>
                    <li>@Html.ActionLink("Get Notes List", "GetNotes", "Notes")</li>
                    <li>@Html.ActionLink("Update Notes", "Update", "Notes")</li>
                    <li>@Html.ActionLink("Delete Notes", "Delete", "Notes")</li>*@

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>